catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - nestjs-indexer
  - playground

patchedDependencies:
  redlock-universal: patches/redlock-universal.patch

catalogs:
  cli:
    '@antfu/eslint-config': ^6.6.1
    '@antfu/ni': ^28.2.0
    bumpp: ^10.4.1
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    publint: ^0.3.17
    simple-git-hooks: ^2.13.1
    tsdown: ^0.17.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.3.1
  inlined:
    '@antfu/utils': ^9.3.0
    dayjs: ^1.11.19
    reflect-metadata: ^0.2.2
    unstorage: ^1.17.4
  runtime:
    '@hairy/lnv': ^9.1.0
    '@hairy/oxrun': ^0.2.8
    '@hairy/utils': ^1.47.0
    '@nestjs/common': ^11.1.13
    '@nestjs/core': ^11.1.13
    '@nestjs/platform-express': ^11.1.13
    '@nestjs/schedule': ^6.1.0
    '@nestjs/swagger': ^11.0.6
    '@nestjs/testing': ^11.1.13
    '@oxc-node/core': ^0.0.35
    ioredis: ^5.9.3
    nestjs-redlock-universal: ^0.3.0
    redlock-universal: ^0.8.2
  testing:
    '@types/ioredis-mock': ^8.2.6
    '@vitest/coverage-v8': ^4.0.18
    ioredis-mock: ^8.13.1
    tinyexec: ^1.0.2
    vitest: ^4.0.18
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^25.2.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
